### ISSUE TITLE
Two bugs I found

### ISSUE THREAD

**Issue by Trnrr** [kyrptonaught/quickshulker#2]
Two bugs:
Having `Right click while hovering in Inventory` and then right clicking it in your inventory and then hitting esc or the inventory key will place the shulker on the ground. 

Another:
Open your inventory (E)
Right clicking the shulker
Hit inventory key (to close)

It will open another menu that you have to close

**Comment by maruohon** [comment]
For me this *sometimes* (inconsistently) happens immediately when you right click a shulker box in your inventory, it will place the item from your selected hotbar slot. So it seems like the right click action sometimes somehow bleeds through to the vanilla right click handling.

**Comment by kyrptonaught** [comment]
I haven't been able to fix this one, but at least its only an annoyance in survival with the dupe-ability contained to creative only. I think it's due to the fact that when you open a new screen there is a few ticks where there is no screen open, thus allowing your right click that most likely is still being activated, to trigger a block place.
