### ISSUE TITLE
[Request] Bundle behaviour for inventories

### ISSUE THREAD

**Issue by Estrelaura** [kyrptonaught/quickshulker#41]
I think a nice alternative for items that store inventories would be allowing the same methods of the bundle, such as dragging the stack into the item or right clicking the item to extract the latest added stack.

**Comment by MeeniMc** [comment]
Dragging the stack into the container is already implemented. 

Right clicking would conflict with the quick-open hovered container on click behavior.

**Comment by kyrptonaught** [comment]
Yes holding a stack and right clicking on a shulker is already supported, but a bit buggy in the current release. I am working on an update with some improvements to this, and brining it to the ender chest and potentially other quick items as well. 

Right clicking the stack to get an item out of it is not an option, since that would interfere with opening it. Maybe holding the shulker and right clicking an empty inventory slot is a better solution?

**Comment by kyrptonaught** [comment]
This was released in 1.3.0
