### ISSUE TITLE
Another duplication issue from a user on our server

### ISSUE THREAD

**Issue by aakova** [kyrptonaught/quickshulker#9]
"the fabric mod has a fatal flaw where it sends packets after the inventory is closed, so if you right click in your inventory while holding it in your hand and aiming at a block, it will open the inventory while placing the shulker box with an identical inventory. basically, it allows for item duping."

Simple as that, put a shulker on your hotbar, aim at a block, press 'e' to enter inventory, right-click the shulker to open.  The shulker will be placed, and you'll still have a copy in your hand.

**Comment by kyrptonaught** [comment]
Ah this is an interesting one. From my testing it seems like you have to have the angle and position in a certain spot in order for it to work, had a hard time getting it consistently to trigger. Gonna investigate why this happens

**Comment by kyrptonaught** [comment]
Really got me scratching my head on this one, I'm sorry for the wait. 

It seems I might have narrowed down the issue. It seems there's a few ticks in between when the players inv screen closes, and when the shulkers inv opens when the user's right click can be triggered. Bit tricky to fix especially since it can't just be a client side fix so users cannot just refuse to update and still continue to abuse the dupe

**Comment by kyrptonaught** [comment]
This has been fixed in 1.1.9. I'm sorry for the delay!
